B2C2Frietzaak/Models/Sauce.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace B2C2Frietzaak.Models
{
    public class Sauce
    {
        public int SauceId { get; set; }
        [Display(Name = "Saus")]
        [Required]
        public string? SauceName { get; set;}
    }
}

B2C2Frietzaak/Controllers/ProductsController.cs
using B2C2Frietzaak.Data;
using B2C2Frietzaak.Data.Migrations;
using B2C2Frietzaak.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace B2C2Frietzaak.Controllers
{
    public class ProductsController : Controller
    {
        //Dependancy Injection
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public ProductsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }
        public Product? Product { get; set; }


        //Product Overview
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ProductsOverview()
        {

            var products = await _context.Products.Include(p => p.Category).ToListAsync();
            return View(products);
        }


        //Products Add
        public async Task<IActionResult> AddProducts(Product product, IFormFile ImageFile)
        {
            // Handle file upload first
            if (ImageFile != null && ImageFile.Length > 0)
            {
                var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                var assetDirectory = Path.Combine(_environment.WebRootPath, "Assets");
                var filePath = Path.Combine(assetDirectory, uniqueFileName);

                if (!Directory.Exists(assetDirectory))
                {
                    Directory.CreateDirectory(assetDirectory);
                }

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(fileStream);
                }

                product.ImageUrl = "Assets/" + uniqueFileName;


                if (ModelState.IsValid) //Gave errors because of "Required" annotation in model
                {
                    _context.Add(product);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("ProductsOverview");
                }
            }
         
            ViewBag.Categories = await _context.Categories.ToListAsync();

            return View(product);
        }



        //Products Edit
        public async Task<IActionResult> EditProducts(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            ViewBag.Categories = await _context.Categories.ToListAsync();
            return View(product);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProducts(int id, Product product, IFormFile ImageFile)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ImageFile != null && ImageFile.Length > 0)
            {
                var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                var assetDirectory = Path.Combine(_environment.WebRootPath, "Assets");
                var filePath = Path.Combine(assetDirectory, uniqueFileName);

                if (!Directory.Exists(assetDirectory))
                {
                    Directory.CreateDirectory(assetDirectory);
                }

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(fileStream);
                }

                product.ImageUrl = "Assets/" + uniqueFileName;

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(product);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductExists(product.ProductId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
                return RedirectToAction("ProductsOverview");
            }

            return View(product);
        }

        //Products Delete
        public async Task<IActionResult> DeleteProducts(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        //Products Delete Confirmation
        [HttpPost, ActionName("DeleteProducts")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'AppDbContext.Products'  is null.");
            }
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("ProductsOverview");
        }

        private bool ProductExists(int id)
        {
            return (_context.Products?.Any(e => e.ProductId == id)).GetValueOrDefault();
        }
    }
}

B2C2Frietzaak/Controllers/SaucesController.cs
using B2C2Frietzaak.Data;
using B2C2Frietzaak.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace B2C2Frietzaak.Controllers
{
    public class SaucesController : Controller
    {
        //Dependancy Injection
        private readonly ApplicationDbContext _context;

        public SaucesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SaucesOverview()
        {
            return _context.Sauces != null ?
                        View(await _context.Sauces.ToListAsync()) :
                        Problem("Entity set 'AppDbContext.Sauce'  is null.");
        }

        public async Task<IActionResult> AddSauce(Sauce sauce)
        {

            if (ModelState.IsValid)
            {
                _context.Add(sauce);
                await _context.SaveChangesAsync();
                return RedirectToAction("SaucesOverview");
            }

            return View(sauce);

        }

        public async Task<IActionResult> EditSauce(int? id)
        {
            if (id == null || _context.Sauces == null)
            {
                return NotFound();
            }

            var sauce = await _context.Sauces.FindAsync(id);
            if (sauce == null)
            {
                return NotFound();
            }

            return View(sauce);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditSauce(int id, Sauce sauce)
        {
            if (id != sauce.SauceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sauce);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SauceExists(sauce.SauceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("SaucesOverview");
            }
            return View(sauce);
        }

        //Sauce Delete
        public async Task<IActionResult> DeleteSauce(int? id)
        {
            if (id == null || _context.Sauces == null)
            {
                return NotFound();
            }

            var sauce = await _context.Sauces
                .FirstOrDefaultAsync(m => m.SauceId == id);
            if (sauce == null)
            {
                return NotFound();
            }

            return View(sauce);
        }

        //Sauce Delete Confirmation
        [HttpPost, ActionName("DeleteSauce")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sauces == null)
            {
                return Problem("Entity set 'AppDbContext.Products'  is null.");
            }
            var sauce = await _context.Sauces.FindAsync(id);
            if (sauce != null)
            {
                _context.Sauces.Remove(sauce);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("SaucesOverview");
        }

        private bool SauceExists(int id)
        {
            return (_context.Sauces?.Any(e => e.SauceId == id)).GetValueOrDefault();
        }

    }
}

B2C2Frietzaak/Views/Sauces/AddSauce.cshtml
@model B2C2Frietzaak.Models.Sauce

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InleveropdrachtB2C2Frietzaak.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body class="bg-dark text-white-50">
    <div class="row mt-5 justify-content-center">
        <div class="col-md-4">
            <form asp-action="AddSauce" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="SauceName" class="control-label"></label>
                    <input asp-for="SauceName" class="form-control" />
                    <input asp-for="SauceId" type="hidden" class="form-control"/>
                    <span asp-validation-for="SauceName" class="text-danger"></span>
                </div>   
                <div class="form-group float-end mt-2">
                    <input type="submit" value="Toevoegen" class="btn btn-outline-success" />
                </div>
            </form>
        </div>
    </div>
</body>
</html> 

B2C2Frietzaak/Views/Sauces/DeleteSauce.cshtml
@model B2C2Frietzaak.Models.Sauce

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InleveropdrachtB2C2Frietzaak.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body class="bg-dark text-white-50">
    <div class="row mt-5 justify-content-center">
        <div class="col-md-4 border rounded">
            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.SauceName)
                </dt>
                <dd class="col-sm-10 text-end">
                    @Html.DisplayFor(model => model.SauceName)
                </dd>
                
            </dl>
            <form class="form-group d-flex m-2 justify-content-between" asp-action="DeleteSauce">
                <button asp-action="SaucesOverview" class="btn btn-outline-secondary">
                    <i class="bi bi-arrow-90deg-left"></i>
                </button>
                <input type="hidden" asp-for="SauceId" />
                <input type="submit" value="Verwijderen" class="btn btn-danger" />
            </form>
        </div>
    </div>
</body>
</html>

B2C2Frietzaak/Views/Sauces/EditSauce.cshtml
@model B2C2Frietzaak.Models.Sauce

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InleveropdrachtB2C2Frietzaak.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
</head>
<body class="bg-dark text-white-50">
    <div class="row mt-5 justify-content-center">
        <div class="col-md-4">
            <form asp-action="EditSauce" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="SauceId" />
                <div class="form-group">
                    <label asp-for="SauceName" class="control-label"></label>
                    <input asp-for="SauceName" class="form-control" />
                    <span asp-validation-for="SauceName" class="text-danger"></span>
                </div>               
                <div class="from-group float-start mt-2">
                    <button asp-action="SaucesOverview" class="btn btn-outline-secondary"><i class="bi bi-arrow-90deg-left"></i></button>
                </div>
                <div class="form-group float-end mt-2">
                    <input type="submit" value="Opslaan" class="btn btn-outline-success" />
                </div>
            </form>
        </div>
    </div>
</body>
</html>

B2C2Frietzaak/Views/Sauces/SaucesOverview.cshtml
@model IEnumerable<B2C2Frietzaak.Models.Sauce>

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InleveropdrachtB2C2Frietzaak.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark text-white-50">
    <div>
        <div class="d-flex justify-content-between">
            <h1>Alle Sauzen</h1>
             </div>
        <table class="table table-dark text-white-50">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.SauceName)
                    </th>
                    <th>
                        Manage
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.SauceName)
                        </td>
                        <td>
                            <a class="btn btn-outline-primary" asp-action="EditSauce" asp-route-id="@item.SauceId">Edit</a>
                            <a class="btn btn-outline-danger" asp-action="DeleteSauce" asp-route-id="@item.SauceId">Delete</a>
                        </td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
    <div class="d-flex justify-content-between">
        <a asp-controller="Products" asp-action="ProductsOverview" class="btn btn-outline-secondary"><i class="bi bi-arrow-90deg-left"></i></a>
        <a asp-controller="Sauces" class="btn btn-outline-success flex-column ms-auto" asp-action="AddSauce">Saus Toevoegen</a>
    </div>

</body>
</html> 